### ISSUE TITLE
How to test on an Emulator?

### ISSUE THREAD

**Issue by Ein-Tim** [ehn-digital-green-development/hcert-app-swift#2]
Hey, thank you for making the development process here Open-Source!

I have a question:

I successfully checked out the main branch and was able to run the app on an Emulator, but there it always just throws this error:
<img src="https://user-images.githubusercontent.com/67682506/119221976-57a1b700-baf2-11eb-92d6-c61cbb4966a9.png" width="300">

Am I doing something wrong? Or is this just not ready yet?

**Comment by asitdm** [comment]
Hi,

I'm afraid you have to run the app on a real device. 

We use `AVCaptureDevice`[here](https://github.com/ehn-digital-green-development/ValidationCore/blob/main/Sources/ValidationCore/QrCodeScanner.swift) for scanning the DGC QR code, which is not supported on the iOS simulator. Because of this being null, the app displays this error (although this should be more descriptive than "User cancelled").

**Comment by Ein-Tim** [comment]
@asitdm Thank you for the answer! I understand that you need this. The error message could be improved, as you said, but I wouldn't consider this as a priority item.
